### ISSUE TITLE
Using the picker controlled makes the marker draggable outside of the saturation spectrum

### ISSUE THREAD

**Issue by prewk** [zippyui/react-color-picker#5]
Hi, I've created a test case for the problem here: [https://github.com/prewk/react-color-picker-problem](https://github.com/prewk/react-color-picker-problem)

It seems like a rather trivial use of the controlled component, am I doing something wrong?

**Comment by zippyui-react** [comment]
Looking into this, and coming back with feedback.
Thanks

**Comment by prewk** [comment]
Thanks a bunch!

**Comment by lPadier** [comment]
These lines in SaturationSpectrum seem weird :
https://github.com/zippyui/react-color-picker/blob/e10ecb06aac/lib/SaturationSpectrum.js#L69-L71

Removing these lines restores proper function.

**Comment by zippyui-react** [comment]
At first sight, they are not needed, but try removing them and dragging the pointer to the bottom-right corner of the spectrum. You'll notice the pointer moves weirdly/not precise, since the same color is present at multiple pixels. Given a color, the formula we're using maps the color to a pixel in the spectrum. So you drag the pointer over a color, it maps to a pixel, but that pixel position is a different one from that of the pointer.Without those lines, the pointer jumps to the pixel computed by the formula (even though, the pointer is at a pixel with the same color).
But yes, those lines may be related to the bug, and actually they probably cause the bug, since the condition in the if statement is not always correct. But the adjustment is needed when state.mouseDown is true.
I will have a look into this and come back with a solution on Monday.

**Comment by zippyui-react** [comment]
I've just published v 2.1.9 to npm, with the fix!

Thanks for reporting!

**Comment by prewk** [comment]
Thank you! :+1:

**Comment by zippyui-react** [comment]
Let us know if you experience any other issues!
